version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
